## Lists, Dictionaries and Sets in Python

## Part 1

### Lists in Python

Sequences in Python are data structures that hold objects in an ordered array. Now, we will work on Lists, the most common sequence data types in Python.

In [163]:
#Example 
l1 = ['learning', "Python", 'is fun?', True]
print(l1)

['learning', 'Python', 'is fun?', True]

List can also be created by using list() function.

In [164]:
#Example
l2 = list(("learning", "for", "life", True))
print(l2)

['learning', 'for', 'life', True]

Adding to an existing list

### Question 1

Add 10 to list l1 given above.

[ **Hint: ** Use **append** ]

In [165]:
l1 = ['learning', "Python", 'is fun?', True]
l1.append(10)
print(l1)

['learning', 'Python', 'is fun?', True, 10]

Removing from an existing list

### Question 2

Remove 10 from l1.

[ **Hint:** Use **remove**]

In [166]:
l1.remove(10)
print(l1)

['learning', 'Python', 'is fun?', True]

Joining 2 lists

### Question 3

[ **Hint: ** Use **+** operator or **extend**]

In [167]:
l1 = ['learning', "Python", 'is fun?', True]
l2 = list(("learning", "for", "life", True))
print (l2)

['learning', 'for', 'life', True]

In [168]:
l1 + l2

['learning', 'Python', 'is fun?', True, 'learning', 'for', 'life', True]

Number List

### Question 4

Find Range and Mean of l3.

l3 = [2,4,6,8]

[ **Hint: ** Use **len(),sum(), min(), max()** functions ]
 
If you want to use standard functions like mean & range, you have to import them from numpy else you can calculate them the traditional way using formulas

In [169]:
l3 = [2,4,6,8]
print("Range:", max(l3) - min(l3))
print("Mean:", sum(l3)/len(l3))

Range: 6
Mean: 5.0

Count the occurances of an element in a given list.

### Question 5
Append the given sequence of numbers to l3 (given above) 0,1,3,3,5,5,7,9. Count the occurences of 5 in l3.

[ **Hint: ** Use ** + operator to add multiple elements in the array and count() function to print the occurences**]

In [170]:
l3 = [2,4,6,8]
l4 = [0,1,3,3,5,5,7,9]
l3 = l3+l4
print(l3)
l3.count(5)

[2, 4, 6, 8, 0, 1, 3, 3, 5, 5, 7, 9]

2

Sorting and Reversing a list

### Question 6
sort and print l3 in ascending and descending order sequentially (given above)

**(Hint: Use .sort() function)**

In [171]:
l3.sort()
print(l3)

[0, 1, 2, 3, 3, 4, 5, 5, 6, 7, 8, 9]

In [172]:
l3.sort(reverse=True)
print(l3)

[9, 8, 7, 6, 5, 5, 4, 3, 3, 2, 1, 0]

### Functions

**Example:**

**def** function_name(args)**:**
    
    function code goes here

### Question 7

Define a function with name **sum_3** which can take 3 numbers as input, and returns sum of them.

In [173]:
def sum_3(n1,n2,n3):
    return(n1+n2+n3)
sum_3(1,2,3)

6

### Lambda Functions

Anonymous functions or no name functions, which can be considered when you use a function only once.

**Example:**

f = lambda x, y : x + y

f(1,1)

2

### Question 8

Write the same above **sum_3** function using lambda.

In [174]:
f= lambda x,y,z:x+y+z
f(2,3,4)

9

# Numpy

We have seen python basic data structures in our last section. They are great but lack specialized features for data analysis. Like, adding roows, columns, operating on 2d matrices aren't readily available. So, we will use *numpy* for such functions.

In [175]:
import numpy as np

Numpy operates on *nd* arrays. These are similar to lists but contains homogenous elements but easier to store 2-d data.

In [176]:
l1 = [1,2,3,4]
nd1 = np.array(l1)
print(nd1)

l2 = [5,6,7,8]
nd2 = np.array([l1,l2])
print(nd2)

[1 2 3 4]
[[1 2 3 4]
 [5 6 7 8]]

Sum functions on np.array()

In [177]:
print(nd2.shape)

print(nd2.size)

print(nd2.dtype)

(2, 4)
8
int64

### Question 1

Create an identity 2d-array or matrix (with ones across the diagonal).

[ **Hint: ** You can also use **np.identity()** function ]

In [178]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Question 2

Create a 2d-array or matrix of order 3x3 with values = 9,8,7,6,5,4,3,2,1 arranged in the same order.

Use: **np.matrix()** function

In [179]:
np.matrix([[9,8,7],[6,5,4],[3,2,1]])

matrix([[9, 8, 7],
        [6, 5, 4],
        [3, 2, 1]])

### Question 3

Reverse both the rows and columns of the given matrix.

Hint: You can use the transpose **.T**)

In [180]:
np.matrix([[9,8,7],[6,5,4],[3,2,1]]).T

matrix([[9, 6, 3],
        [8, 5, 2],
        [7, 4, 1]])

### Question 4
Add + 1 to all the elements in the given matrix.

In [181]:
np.matrix([[9,8,7],[6,5,4],[3,2,1]]) +1

matrix([[10,  9,  8],
        [ 7,  6,  5],
        [ 4,  3,  2]])

Similarly you can do operations like scalar  substraction, division, multiplication (operating on each element in the matrix)

### Question 5

Find the mean of all elements in the given matrix nd6.
nd6 = [[  1   4   9 121 144 169]
 [ 16  25  36 196 225 256]
 [ 49  64  81 289 324 361]]
 
 Use: **.mean()** function

In [182]:
nd6=[[1,4,9,121,144,169],
 [16,25,36,196,225,256],
 [49,64,81,289,324,361]]
np.mean(nd6)

131.66666666666666

### Question 7

Find the dot product of two given matrices.

[**Hint:** Use **np.dot()**]

In [183]:
nd6=[[1,2,3],
 [3,4,5],
 [5,6,7]]
nd7=[[1,2],
 [6,7],
 [9,4]]
np.dot(nd6,nd7)

array([[ 40,  28],
       [ 72,  54],
       [104,  80]])

# Pandas

We have seen Numpy in the last section. It is good at performing math operation on 2d-arrays of numbers. But the major drawback is, it cannot deal with heterogenous values. So, Pandas dataframes are helpful in that aspect for storing different data types and referring the values like a dict in python instead of just referring each item with index.

[Link to Official Documentation](http://pandas.pydata.org/pandas-docs/version/0.23/dsintro.html)

## Series

Pandas series are almost same as nd arrays in numpy, with a additional inferencing ability with custom labels like *keys* in a *dictionary* in python.

In [184]:
import numpy as np
import pandas as pd

In [185]:
#Example

series1 = pd.Series(data = [1,2,3], index = ['key1', 'key2', 'key3'])
series1

key1    1
key2    2
key3    3
dtype: int64

### Question 1

Convert a given dict to pd series.

[**Hint:** Use **.Series**]

In [186]:
import pandas as pd
d1 = {'a': 1, 'b': 2, 'c': 3}
series2 = pd.Series(d1)
print(series2)

a    1
b    2
c    3
dtype: int64

You can directly use numpy functions on series.
### Question 2

Find the dot product of both the series create above


[ **Hint: ** Use **np.dot()** ]

In [187]:
np.dot(series1,series2)

14

## Dataframes

A dataframe is a table with labeled columns which can hold different types of data in each column.

In [188]:
# Example
d1 = {'a': [1,2,3], 'b': [3,4,5], 'c':[6,7,8] }
df1 = pd.DataFrame(d1)
df1

   a  b  c
0  1  3  6
1  2  4  7
2  3  5  8

### Question 3

Select second row in the above dataframe df1.

In [189]:
df1.loc[1]

a    2
b    4
c    7
Name: 1, dtype: int64

### Question 4

Select column c in second row of df1.

[ **Hint: ** For using labels use **df.loc[row, column]**. For using numeric indexed use **df.iloc[]**. For using mixture of numeric indexes and labels use **df.ix[row, column]** ]

In [190]:
df1.loc[1,'c']

7

## Using Dataframes on a dataset

##### Using the mtcars dataset.

For the below set of questions, we will be using the cars data from [Motor Trend Car Road Tests](http://stat.ethz.ch/R-manual/R-devel/library/datasets/html/mtcars.html)

The data was extracted from the 1974 Motor Trend US magazine, and comprises fuel consumption and 10 aspects of automobile design and performance for 32 automobiles (1973–74 models). 


Details :
    
A data frame with 32 observations on 11 (numeric) variables.

[, 1] 	mpg 	Miles/(US) gallon

[, 2] 	cyl 	Number of cylinders

[, 3] 	disp 	Displacement (cu.in.)

[, 4] 	hp 	Gross horsepower

[, 5] 	drat 	Rear axle ratio

[, 6] 	wt 	Weight (1000 lbs)

[, 7] 	qsec 	1/4 mile time

[, 8] 	vs 	Engine (0 = V-shaped, 1 = straight)

[, 9] 	am 	Transmission (0 = automatic, 1 = manual)

[,10] 	gear 	Number of forward gears

[,11] 	carb 	Number of carburetors

In [191]:
import pandas as pd
## Reading a dataset from a csv file using pandas.
mtcars = pd.read_csv('../input/mtcars.csv')
mtcars.index = mtcars['name']

Following questions are based on analysing a particular dataset using dataframes.

### Question 5

Check the type and dimensions of given dataset - mtcars.


[ **Hint: ** Use **type()** and **df.shape** ]

In [192]:
mtcars.head()

                                name   mpg  cyl   disp  ...   vs  am  gear  carb
name                                                    ...
Mazda RX4                  Mazda RX4  21.0    6  160.0  ...    0   1     4     4
Mazda RX4 Wag          Mazda RX4 Wag  21.0    6  160.0  ...    0   1     4     4
Datsun 710                Datsun 710  22.8    4  108.0  ...    1   1     4     1
Hornet 4 Drive        Hornet 4 Drive  21.4    6  258.0  ...    1   0     3     1
Hornet Sportabout  Hornet Sportabout  18.7    8  360.0  ...    0   0     3     2

[5 rows x 12 columns]

### Question 6

Check the first 10 lines and last 10 lines of the given dataset- mtcars.

[**Hint:** Use **.head()** and **.tail()**]

In [193]:
mtcars.head(10)

                                name   mpg  cyl   disp  ...   vs  am  gear  carb
name                                                    ...
Mazda RX4                  Mazda RX4  21.0    6  160.0  ...    0   1     4     4
Mazda RX4 Wag          Mazda RX4 Wag  21.0    6  160.0  ...    0   1     4     4
Datsun 710                Datsun 710  22.8    4  108.0  ...    1   1     4     1
Hornet 4 Drive        Hornet 4 Drive  21.4    6  258.0  ...    1   0     3     1
Hornet Sportabout  Hornet Sportabout  18.7    8  360.0  ...    0   0     3     2
Valiant                      Valiant  18.1    6  225.0  ...    1   0     3     1
Duster 360                Duster 360  14.3    8  360.0  ...    0   0     3     4
Merc 240D                  Merc 240D  24.4    4  146.7  ...    1   0     4     2
Merc 230                    Merc 230  22.8    4  140.8  ...    1   0     4     2
Merc 280                    Merc 280  19.2    6  167.6  ...    1   0     4     4

[10 rows x 12 columns]

In [194]:
mtcars.tail(10)

                              name   mpg  cyl   disp  ...   vs  am  gear  carb
name                                                  ...
AMC Javelin            AMC Javelin  15.2    8  304.0  ...    0   0     3     2
Camaro Z28              Camaro Z28  13.3    8  350.0  ...    0   0     3     4
Pontiac Firebird  Pontiac Firebird  19.2    8  400.0  ...    0   0     3     2
Fiat X1-9                Fiat X1-9  27.3    4   79.0  ...    1   1     4     1
Porsche 914-2        Porsche 914-2  26.0    4  120.3  ...    0   1     5     2
Lotus Europa          Lotus Europa  30.4    4   95.1  ...    1   1     5     2
Ford Pantera L      Ford Pantera L  15.8    8  351.0  ...    0   1     5     4
Ferrari Dino          Ferrari Dino  19.7    6  145.0  ...    0   1     5     6
Maserati Bora        Maserati Bora  15.0    8  301.0  ...    0   1     5     8
Volvo 142E              Volvo 142E  21.4    4  121.0  ...    1   1     4     2

[10 rows x 12 columns]

### Question 7

Print all the column labels in the given dataset - mtcars.

[ **Hint: ** Use **df.columns** ]

In [195]:
mtcars.columns

Index(['name', 'mpg', 'cyl', 'disp', 'hp', 'drat', 'wt', 'qsec', 'vs', 'am',
       'gear', 'carb'],
      dtype='object')

### Question 8

Select first 6 rows and 3 columns in mtcars dataframe.

**Hint: **  
mtcars.ix[:,:] gives all rows and columns in the dataset.

In [196]:
mtcars.iloc[:6,:3]

                                name   mpg  cyl
name
Mazda RX4                  Mazda RX4  21.0    6
Mazda RX4 Wag          Mazda RX4 Wag  21.0    6
Datsun 710                Datsun 710  22.8    4
Hornet 4 Drive        Hornet 4 Drive  21.4    6
Hornet Sportabout  Hornet Sportabout  18.7    8
Valiant                      Valiant  18.1    6

## Lab Brief - Statistical Learning with Python

### Part-1

## Measures of Data

Descriptive Statistcs are measures that summarize important features of data. Producing these descriptive statistics is a common first step to take after cleaning and preparing a dataset for further analysis. Examples are like calculating Mean or Median. In this lab, we will be looking into some of these functions and explore several new ones.

#### Measures of Central Tendency

Whenever you measure things of the same kind, a fairly large number of such measurements will tend to cluster around the middle value. Such a value is called a measure of "Central Tendency". The other terms that are used synonymously are "Measures of Location", or "Statistical Averages".

In [197]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

mtcars = pd.read_csv('mtcars.csv')

FileNotFoundError: File b'mtcars.csv' does not exist

##### Using the mtcars dataset.

For the below set of questions, we will be using the cars data from [Motor Trend Car Road Tests](http://stat.ethz.ch/R-manual/R-devel/library/datasets/html/mtcars.html)

The data was extracted from the 1974 Motor Trend US magazine, and comprises fuel consumption and 10 aspects of automobile design and performance for 32 automobiles (1973–74 models). 


Details :
    
A data frame with 32 observations on 11 (numeric) variables.

[, 1] 	mpg 	Miles/(US) gallon

[, 2] 	cyl 	Number of cylinders

[, 3] 	disp 	Displacement (cu.in.)

[, 4] 	hp 	Gross horsepower

[, 5] 	drat 	Rear axle ratio

[, 6] 	wt 	Weight (1000 lbs)

[, 7] 	qsec 	1/4 mile time

[, 8] 	vs 	Engine (0 = V-shaped, 1 = straight)

[, 9] 	am 	Transmission (0 = automatic, 1 = manual)

[,10] 	gear 	Number of forward gears

[,11] 	carb 	Number of carburetors

#### Explore the data - Setting the index

In [ ]:
mtcars.index = mtcars["name"]
mtcars.head()
# mtcars.mean() #By default this will give the mean of each column

### Question 1

What is the first car name given in mtcars?

** Make use of index which has been set previously **

**Hint**: Use .loc function

In [ ]:
mtcars['name'][0]

In [ ]:
mtcars['name'][1]

In [ ]:
mtcars.name[1]

### Question 2
What is the highest difference between the hp and cyl?

**Hint:** You can use **max()** function to find the difference

In [ ]:
max((mtcars.hp) - (mtcars.cyl))

### Question 3
What are the cars having highest weight(wt) and lowest weight(wt)?

**Hint:** Use idxmax() and idxmin() to locate the row

Use **.iloc** function to print the  row

**Note:** Both idxmax and idxmin belong to pandas

In [ ]:
mtcars['name'][mtcars['wt'].idxmax()]

In [ ]:
mtcars['name'][mtcars['wt'].idxmin()]

### Question 4

Find the mean of each row and each column in the given dataset.

**Hint:** Use .mean() function. To operate on rows use **axis=0**, on columns use **axis=1**

In [ ]:
mtcars.mean(axis=0)

In [ ]:
mtcars.mean(axis=1)

### Question 5

Plot mpg values of mtcards dataframe using matplotlib.

**Hint: Use plt.plot function**

In [ ]:
import matplotlib.pyplot as plt
plt.plot(mtcars['name'],mtcars['mpg'])
locs, labels = plt.xticks()
plt.setp(labels, rotation=90)
plt.show()

## Part 2

## Measures of Dispersion

Measures of Dispersion (Spread) are statistics that describe how data varies. Measure of dispersion gives us the sense of how much the data tends to diverge from the central tendency.

### Question 6

What the range of `mpg` in the given dataset?

**Hint:** Range = max-min

In [ ]:
max(mtcars.mpg)-min(mtcars.mpg)

### Question 7

Calculate the 25th quantile (lower quantile)for `mpg` in the given dataset.

**Hint:** Use **.quantile()**

In [ ]:
mtcars['mpg'].quantile(0.25)

### Question 8

Calculate the Inter-Quartile Range(IQR) for `mpg` in the given dataset.

Interquartile range (IQR) is another common measure of spread. IQR is the distance between the 3rd quartile and the 1st quartile.

**Hint:** IQR = Q3 - Q1

In [ ]:
mtcars['mpg'].quantile(0.75)

In [ ]:
mtcars['mpg'].quantile(0.75)-mtcars['mpg'].quantile(0.25)

### Question 9

Calculate the Variance, Standard Deviation and Median Absolute Deviation for `mpg`.

Variance and Standard Deviation are two other common measure of dispersion.

**Hint:** Use .var() and .std()

**Hint:** Median Absolute Deviation - alternative measure of spread based on the median. It is the median of the absolute value of the deviations from the median.

In [ ]:
mtcars['mpg'].var()